# Snakemake config for Iceman analysis
# Intended for use on CTMR-NAS
# (c) Fredrik Boulund 2017

samples: 
    "224"
background_sample: 
    "1018"
samples_dir:
    /home/ctmr/projects/iceman/samples/

bbduk_human_db_path:
    /home/ctmr/db/hg19
bbduk_ref:
    /home/ctmr/db/bbmap_resources/adapters.fa
hg19_fasta:
    /home/ctmr/db/hg19/hg19_main_mask_ribo_animal_allplant_allfungus.fa
mpa_pkl:
    /home/ctmr/db/metaphlan2/db_v20/mpa_v20_m200.pkl
mpa_bowtie2db:
    /home/ctmr/db/metaphlan2/db_v20/mpa_v20_m200
megares_fasta:
    /home/ctmr/db/MEGARes/latest/megares_database_v1.01.fasta
megares_annotations:
    /home/ctmr/db/MEGARes/latest/megares_annotations_v1.01.csv
